# -*- coding: utf-8 -*-
"""Tracking_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/freida20git/bird-detection-tracking/blob/main/Tracking_metrics.ipynb

#**MOT Metrics to calculate how good is the tracking of the birds**

NOTE:
this metrics do not compare the ID numbers directly. The tracker evaluation does not care if your predicted IDs are 1, 100, or 9999. What is measured is how consistently a predicted ID is matched to a ground truth ID across frames based on bounding box overlaps (IoU).

 so its not a problem if youre predictions have different ID numbers than ground truth.
"""

#!pip install ultralytics==8.0.122
#!pip install ultralytics
#!pip install motmetrics

"""Tracking annotations(prediction and ground truth) in json format (created in tracker.py notebook):

"""

pred_annotations ="/content/pred_annotations.json"
gt_annotations = "/content/annotations_gt.json"


import random
import cv2
import torch
import ultralytics
ultralytics.checks()
from ultralytics import YOLO
from IPython.display import Image
from collections import defaultdict
import numpy as np
import motmetrics as mm
import pandas as pd
import json
import os
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval


def convert_json_to_mot(json_path, output_path):
    with open(json_path, "r") as f:
        data = json.load(f)

    with open(output_path, "w") as f_out:
        for frame in data:
            frame_number = frame["frame_number"]
            for obj in frame["objects"]:
                track_id = obj["track_id"]
                confidence = obj["confidence"]
                class_id = obj["class_id"]

                # Extract bounding box
                x1, y1 = obj["bbox"]["x1"], obj["bbox"]["y1"]
                x2, y2 = obj["bbox"]["x2"], obj["bbox"]["y2"]

                # Convert to MOT format (x, y, width, height)
                width, height = x2 - x1, y2 - y1

                # Write in MOT format
                f_out.write(f"{frame_number},{track_id},{x1},{y1},{width},{height},{confidence},{class_id},1\n")

# Example Usage
#convert_json_to_mot("annotations_gt.json", "gt_mot.txt")
#convert_json_to_mot('/content/pred_annotations.json', "pred_annotations.txt")

def compute_tracking_metrics(gt_file, pred_file):
    acc = mm.MOTAccumulator(auto_id=True)

    # Load GT and prediction files
    gt_data = pd.read_csv(gt_file, header=None)
    pred_data = pd.read_csv(pred_file, header=None)

    frames = sorted(set(gt_data[0]) | set(pred_data[0]))

    for frame in frames:
        gt_frame = gt_data[gt_data[0] == frame]
        pred_frame = pred_data[pred_data[0] == frame]

        gt_ids = gt_frame[1].tolist()
        pred_ids = pred_frame[1].tolist()

        def iou(boxA, boxB):
            xA, yA, wA, hA = boxA
            xB, yB, wB, hB = boxB
            x1, y1 = max(xA, xB), max(yA, yB)
            x2, y2 = min(xA + wA, xB + wB), min(yA + hA, yB + hB)
            interArea = max(0, x2 - x1) * max(0, y2 - y1)
            boxAArea = wA * hA
            boxBArea = wB * hB
            return 1 - (interArea / float(boxAArea + boxBArea - interArea))

        gt_boxes = gt_frame.iloc[:, 2:6].values.tolist()
        pred_boxes = pred_frame.iloc[:, 2:6].values.tolist()
        distance_matrix = [[iou(gt, pred) for pred in pred_boxes] for gt in gt_boxes]
        # Creates a cost matrix where:
        # Rows = Ground truth objects.
        # Columns = Predicted objects.
        # Each cell stores the distance (1 - IoU).
        acc.update(gt_ids, pred_ids, distance_matrix)

    mh = mm.metrics.create()
    summary = mh.compute(acc, metrics=['idf1', 'mota', 'motp', 'num_switches'], name="Tracking")
    print(summary)
    return summary

#compute_tracking_metrics("/content/gt_mot.txt", "/content/pred_annotations.txt")

"""1. IDF1 (Identity F1 Score)
Measures how well the predicted identities match the ground truth identities.

2. MOTA (Multiple Object Tracking Accuracy)
Measures overall tracking performance by penalizing missed detections, false positives, and identity switches.

3. MOTP (Multiple Object Tracking Precision)
Measures the localization precision of tracked objects.
It calculates the average overlap (IoU) between matched predictions and ground truth across all frames.

Interpretation of Results:

High IDF1 → The tracker maintains object identities correctly.

High MOTA → The tracker has fewer false positives, false negatives, and ID switches.

Low MOTP → The tracker’s bounding boxes are well-aligned with the ground truth.

# turn into coco format for mAP calculation:
"""

def get_video_resolution(video_path):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Unable to open video: {video_path}")
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    cap.release()
    return width, height

def convert_to_coco_gt(data, width, height):
    coco_gt = {
        "info": {},
        "licenses": [],
        "images": [],
        "annotations": [],
        "categories": [{"id": 0, "name": "Bird"}]
    }

    for frame in data:
        image_id = frame["frame_number"]
        coco_gt["images"].append({
            "id": image_id,
            "file_name": f"frame_{image_id:04d}.jpg",
            "width": width,
            "height": height,
        })

        for obj in frame["objects"]:
            x1, y1, x2, y2 = obj["bbox"]["x1"], obj["bbox"]["y1"], obj["bbox"]["x2"], obj["bbox"]["y2"]
            coco_gt["annotations"].append({
                "id": len(coco_gt["annotations"]),
                "image_id": image_id,
                "category_id": obj["class_id"],
                "bbox": [x1, y1, x2 - x1, y2 - y1],
                "area": (x2 - x1) * (y2 - y1),
                "iscrowd": 0,
            })

    return coco_gt

def convert_predictions_to_coco(data):
    coco_list = []
    for frame in data:
        for obj in frame["objects"]:
            x1, y1, x2, y2 = obj["bbox"]["x1"], obj["bbox"]["y1"], obj["bbox"]["x2"], obj["bbox"]["y2"]
            coco_list.append({
                "image_id": frame["frame_number"],
                "category_id": 0,
                "bbox": [x1, y1, x2 - x1, y2 - y1],
                "score": obj["confidence"],
            })
    return coco_list

def map_calc_coco(gt_json_path, pred_json_path, video_path,
                  coco_gt_path="temp_coco_gt.json", coco_pred_path="temp_coco_pred.json"):
    # Load data
    with open(gt_json_path) as f:
        gt_data = json.load(f)
    with open(pred_json_path) as f:
        pred_data = json.load(f)

    # Get video resolution
    width, height = get_video_resolution(video_path)

    # Convert GT and predictions
    coco_gt = convert_to_coco_gt(gt_data, width, height)
    coco_preds = convert_predictions_to_coco(pred_data)

    # Save intermediate COCO JSONs
    with open(coco_gt_path, "w") as f:
        json.dump(coco_gt, f)
    with open(coco_pred_path, "w") as f:
        json.dump(coco_preds, f)

    # Evaluate
    coco_gt_obj = COCO(coco_gt_path)
    coco_pred_obj = coco_gt_obj.loadRes(coco_pred_path)
    coco_eval = COCOeval(coco_gt_obj, coco_pred_obj, "bbox")
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()

    # Return mAP@[.5:.95] and mAP@0.5
    return coco_eval.stats[0], coco_eval.stats[1]


'''
usage example:
map_5095, map_50 = map_calc_coco(
    gt_json_path="/content/ground truth/gt_birds_sky.json",
    pred_json_path="/content/pred_annotation.json",
    video_path="/content/videos /birds_sky.mp4"
)
print(f"mAP@0.50: {map_50:.4f}")
print(f"mAP@0.50:0.95: {map_5095:.4f}")

'''
